import React from 'react'
import './Color.css'
import Img3 from '../../assets/img3.png'
import { motion } from "framer-motion"


export const Color = () => {
  return (
    <section id="color">
        <div className="color">
            <div className="left-color">
                <motion.img 
                initial={{ scale: 0.5 }}
                whileInView={{ scale: 1 }}
                transition={{ duration: 1 }}
                src={Img3} alt="" />
            </div>
            <motion.div 
             initial={{ scale: 0.5 }}
             whileInView={{ scale: 1 }}
             transition={{ duration: 1 }}
            className="right-color">
                <h2>FROM MILAN DESIGN WEEK</h2>
                <h1>INTERIOR COLOR</h1>
                <h1>TRENDS 2020</h1>
                <div className="text-color">
                    <span>I love to observe how the colour trends that we </span>
                    <span>see are always the consequence of bigger trends,</span> 
                    <span>which are generated by macro changes in our society, </span>
                    <span>interest, behaviours. As a consequence, they are reflected </span>
                    <span>into new shapes, new colours...</span>              
                </div>
            </motion.div>
            <div  className="bg-color"></div>
        </div>
    </section>
  )
}
